
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "hostpah-kubernetes-webhook.acme.com"
  annotations:
    cert-manager.io/inject-ca-from: default/client
webhooks:
  - name: "hostpah-kubernetes-webhook.acme.com"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: hostpah-kubernetes-webhook
        path: /validate-pods
        port: 443
    sideEffects: None
    admissionReviewVersions: ["v1"]